name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install tools
        run: python -m pip install --upgrade pip pytest
        
      - name: Install request
        run: pip install requests

      - name: Install panda
        run: pip install pandas
        
      - name: Install sqlalchemy
        run: pip install sqlalchemy
        
      - name: Install IPython
        run: pip install IPython
        
      - name: Install matplotlib
        run: pip install matplotlib
        
      - name: Install tools
        run: |
          python -m pip install --upgrade pip pytest
          pip install coverage  

      - name: Test with unittest
        run: |
          python3 -m unittest test.py
          
      - name: Check code coverage                        #new from here down
        run: |
          python3 -m coverage run -m unittest test.py
          python3 -m coverage report
          python3 -m coverage html
          
      - name: Archive code coverage HTML report
        uses: actions/upload-artifact@v2
        with:
           name: code-coverage-report
           path: htmlcov